export const fallbackQuestions = {
  Behavioral: [
    'Tell me about a time you faced a difficult challenge at work.',
    'Describe a situation where you had to work with a difficult teammate.',
    'Give an example of a goal you set and how you achieved it.',
    'Tell me about a time you failed and what you learned.',
    'Describe a time you had to learn something quickly.',
    'Tell me about a time you led a team.',
    'Describe a conflict resolution you handled.',
    'Tell me about your proudest professional achievement.',
  ],
  Technical: [
    'Explain the difference between SQL and NoSQL databases.',
    'How does the event loop work in JavaScript?',
    'What is the time complexity of binary search?',
    'Explain RESTful API principles.',
    'What is the difference between TCP and UDP?',
    'How would you design a URL shortener?',
    'Explain how garbage collection works.',
    'What are design patterns? Give examples.',
  ],
  HR: [
    'Tell me about yourself.',
    'Why do you want to work for our company?',
    'Where do you see yourself in five years?',
    'What are your strengths and weaknesses?',
    'Why are you leaving your current job?',
    'What are your salary expectations?',
    'Why should we hire you?',
    'Do you have any questions for us?',
  ],
  Mixed: [
    'Tell me about yourself.',
    'Describe a challenging technical problem you solved.',
    'Why do you want this role?',
    'How do you handle tight deadlines?',
    'What are your technical strengths?',
    'Describe your ideal work environment.',
    'Tell me about a time you disagreed with your manager.',
    'What is your biggest professional weakness?',
  ],
};